### ISSUE TITLE
Plugin seems to not do anything.

### ISSUE THREAD

**Issue by BobaPearl** [imperator-maximus/stable-diffusion-krita#1] opened 2022-09-05 02:38 UTC
Program will not connect to colab or localhost, both have been tested and can be connected too through browser.

**Comment by the0ckid82** [comment] 2022-09-05 05:35
i was having the same issue when trying to use localhost, my issue was resolved by removing the trailing /  
`http://localhost:7860`  vs `http://localhost:7860/`
removing the last `/` fixed the issue for me

**Comment by XodrocSO** [comment] 2022-09-05 05:50
@the0ckid82 Was hoping that fix would work for me but did not.   

Using the webui in the browser works fine, mostly(inpainting doesn't seem to work there).  Installed locally on Windows 10 here. 

![SDKrita-error](https://user-images.githubusercontent.com/7324802/188369407-7691a4b1-6452-4b80-8a79-07a383c09aae.png)

**Comment by BobaPearl** [comment] 2022-09-05 06:45
That didn't work for me either

**Comment by imperator-maximus** [comment] 2022-09-05 10:45
Which Colab you have tried - the one I have provided? https://colab.research.google.com/drive/1BKkFN5OOXydrFAxYJcbPdGrVuQVdJpt_

**Comment by XodrocSO** [comment] 2022-09-05 11:17
Personally I haven't tried Colab at all, followed the local manual install instructions since I have an RTX 3090.  Or is Colab required in addition to the local install?  

Also getting an SSL error:

> Unable to make connection to https://127.0.0.1:7860/api/predict/, Reason: Traceback (most recent call last):
  File "urllib\request.py", line 1319, in do_open
  File "http\client.py", line 1230, in request
  File "http\client.py", line 1276, in _send_request
  File "http\client.py", line 1225, in endheaders
  File "http\client.py", line 1004, in _send_output
  File "http\client.py", line 944, in send
  File "http\client.py", line 1399, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

**Comment by BobaPearl** [comment] 2022-09-05 11:50
> Which Colab you have tried - the one I have provided? https://colab.research.google.com/drive/1BKkFN5OOXydrFAxYJcbPdGrVuQVdJpt_

Yes.

**Comment by BobaPearl** [comment] 2022-09-05 11:58
I also have a 3090, and would prefer to get it going locally over colab, but understand if that mode isn't supported yet.

**Comment by BobaPearl** [comment] 2022-09-05 12:25
Running Krita as administrator has fixed my issue.

**Comment by XodrocSO** [comment] 2022-09-05 13:30
Hmm, tried running as admin, didn't fix it for me, but did get rid of the SSL error.  I can open a new ticket if need be.

**Comment by XodrocSO** [comment] 2022-09-05 22:20
So I noticed when the plugin fails to connect, I get an error in my powershell/conda prompt.  So maybe it's not actually failing to connect in my case..  I'm running the WebUI in a conda environment, which works fine, and have other versions of SD running in Conda environments as well, but maybe it's causing an issue with the Krita plugin? 

> Traceback (most recent call last):
  File "H:\.conda\envs\Krita\lib\site-packages\gradio\routes.py", line 259, in run_predict
    output = await app.blocks.process_api(
  File "H:\.conda\envs\Krita\lib\site-packages\gradio\blocks.py", line 685, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "H:\.conda\envs\Krita\lib\site-packages\gradio\blocks.py", line 591, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "H:\.conda\envs\Krita\lib\site-packages\gradio\components.py", line 1061, in preprocess
    return self.choices.index(x)
ValueError: False is not in list

**Comment by lunaticstraydog** [comment] 2022-09-06 12:06
Same error here, on a local stable diffusion installation on linux.  
Stable Diffusion works fine on webui, however an error occurs when krita does the call.
Here are two separate error logs :
- One from 'script error' window on krita side :
```
TypeError
Python 3.10.6: /usr/bin/python3
Tue Sep  6 13:34:29 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/lucas/.local/share/krita/pykrita/stable_diffusion_krita/sd_main.py in TxtToImage()
  672         p.cfg_value=data["cfg_value"]
  673         images = runSD(p)
  674         imageResultDialog( images,p)
  675 
  676 
global imageResultDialog = <function imageResultDialog>
images = None
p = <stable_diffusion_krita.sd_main.SDParameters object>

 /home/lucas/.local/share/krita/pykrita/stable_diffusion_krita/sd_main.py in imageResultDialog(qImgs=None, p=<stable_diffusion_krita.sd_main.SDParameters object>)
  510 
  511 def imageResultDialog(qImgs,p):
  512     dlg = showImages(qImgs,p)
  513     if dlg.exec():
  514         print("HQ Update here")
dlg undefined
global showImages = <class 'stable_diffusion_krita.sd_main.showImages'>
qImgs = None
p = <stable_diffusion_krita.sd_main.SDParameters object>

 /home/lucas/.local/share/krita/pykrita/stable_diffusion_krita/sd_main.py in __init__(self=<stable_diffusion_krita.sd_main.showImages object>, qImgs=None, p=<stable_diffusion_krita.sd_main.SDParameters object>)
  429         self.qImgs=qImgs
  430         i=0
  431         for qImg in qImgs:
  432             v_layout = QVBoxLayout()
  433             layout.addLayout(v_layout)
qImg undefined
qImgs = None
TypeError: 'NoneType' object is not iterable
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'NoneType' object is not iterable",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/lucas/.local/share/krita/pykrita/stable_diffusion_krita/sd_main.py", line 674, in TxtToImage
    imageResultDialog( images,p)
  File "/home/lucas/.local/share/krita/pykrita/stable_diffusion_krita/sd_main.py", line 512, in imageResultDialog
    dlg = showImages(qImgs,p)
  File "/home/lucas/.local/share/krita/pykrita/stable_diffusion_krita/sd_main.py", line 431, in __init__
    for qImg in qImgs:
TypeError: 'NoneType' object is not iterable

``` 
- One on the (local) server side :
``` Traceback (most recent call last):
  File "/home/lucas/Documents/StableDiffusion/stable_diff_env/lib/python3.10/site-packages/gradio/routes.py", line 259, in run_predict
    output = await app.blocks.process_api(
  File "/home/lucas/Documents/StableDiffusion/stable_diff_env/lib/python3.10/site-packages/gradio/blocks.py", line 685, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/lucas/Documents/StableDiffusion/stable_diff_env/lib/python3.10/site-packages/gradio/blocks.py", line 591, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "/home/lucas/Documents/StableDiffusion/stable_diff_env/lib/python3.10/site-packages/gradio/components.py", line 1061, in preprocess
    return self.choices.index(x)
ValueError: False is not in list
Traceback (most recent call last):
  File "/home/lucas/Documents/StableDiffusion/stable_diff_env/lib/python3.10/site-packages/gradio/routes.py", line 259, in run_predict
    output = await app.blocks.process_api(
  File "/home/lucas/Documents/StableDiffusion/stable_diff_env/lib/python3.10/site-packages/gradio/blocks.py", line 685, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/lucas/Documents/StableDiffusion/stable_diff_env/lib/python3.10/site-packages/gradio/blocks.py", line 591, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "/home/lucas/Documents/StableDiffusion/stable_diff_env/lib/python3.10/site-packages/gradio/components.py", line 1061, in preprocess
    return self.choices.index(x)
ValueError: False is not in list```

**Comment by LoopControl** [comment] 2022-09-07 03:30
I'm getting a very similar error as @lunaticstraydog on Colab -- Always gives HTTP 500 internal server error on Krita side.

On the Colab notebook, there's the following output:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 260, in run_predict
    fn_index, raw_input, username, session_state
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 685, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 591, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "/usr/local/lib/python3.7/dist-packages/gradio/components.py", line 1061, in preprocess
    return self.choices.index(x)
ValueError: False is not in list
```

**Comment by LoopControl** [comment] 2022-09-07 04:03
Did some debugging and I got it working with a code change. The problem is the JSON parameters passed to `/api/predict/` are slightly wrong. Changing `sd_main.py`'s `def runSD(` function around like 594 to the following fixed it:

```
if (p.mode=="txt2img"):
        j={
            "fn_index":2,
            "data":[p.prompt,"",p.steps,p.sampling_method,False,p.num,1,p.cfg_value,seed,SDConfig.height,SDConfig.width,"None","Seed","","Steps","",False]
        }
```

The above fixes txt2img. The others methods (inpainting and img2img) probably need a similar reordering of the JSON but it's late so I'll work on fixing those tomorrow. Excited to start playing with it more indepth then also!

**Comment by AxelFar94** [comment] 2022-09-07 16:08
Just to add to @LoopControl, if you change it the way you did, you break the Localhost, apparently localhost and Colab use different parameters orders, the other modes have Localhost and Colab separated on code, but txt2img don't, but if we add it, it works, just tested Locally and with Colab here and both are working. Locally using `http://localhost:7860` instead of `http://localhost:7860/` as @the0ckid82 said did the trick.
So to have the two working it need to be like this:

```
   if (p.mode=="txt2img"):
 	   # localhost
        j={
            "fn_index":2,
            "data":[p.prompt,"",p.steps,p.sampling_method,False,p.num,1,p.cfg_value,seed,SDConfig.height,SDConfig.width,"None",False,"Seed","","Steps",""]
        }
        # colab
        if (Colab):
            j={
                "fn_index":2,
            "data":[p.prompt,"",p.steps,p.sampling_method,False,p.num,1,p.cfg_value,seed,SDConfig.height,SDConfig.width,"None","Seed","","Steps","",False]
        }         
    headers = {
```
We just need to find and change the Colab parameters order of the other modes, as i don't know how to do it.

**Comment by AxelFar94** [comment] 2022-09-07 16:41
Ok, adding to @LoopControl, changing it the way you did it breaks the localhost, apparently localhost and Colab use different parameters orders, the other modes have Localhost and Colab separated on code, but txt2img don't, so we need to add it.
I've found out that the only parameter that needs reorder it's the "false" parameter, it needs to be in the end of the line on the Colab code of every mode. this fixed it all and now both Local and Colab are fully working for me. To run locally, using http://localhost:7860 instead of http://localhost:7860/ as @the0ckid82 said did the trick.
So the code on `sd_main.py` needs to be like this:
```
if (p.mode=="img2img"):
        # localhost
        j={
            "fn_index":8,
            "data":[p.prompt,p.image64,{"image":p.image64,"mask":p.image64},p.steps,p.sampling_method,4,"latent noise",False,"Redraw whole image",
                    p.num,1,p.cfg_value,p.strength,seed,SDConfig.height,SDConfig.width,"Just resize","RealESRGAN",64,True,
                    "Inpaint masked","None",8,4,"fill",False,"Seed","","Steps",""
            ]
        }
        # colab
        if (Colab):
            j={
                "fn_index":8,
                "data":[p.prompt,p.image64,None,p.steps,p.sampling_method,4,"latent noise",False,"Redraw whole image",
                        p.num,1,p.cfg_value,p.strength,seed,SDConfig.height,SDConfig.width,"Just resize","RealESRGAN",64,False,
                        "Inpaint masked","None",8,4,"fill","Seed","","Steps","",False
                ]
            }        


    if (p.mode=="inpainting"):
        # localhost
        j={
            "fn_index":8,
            "data":[p.prompt,None,{"image":p.image64,"mask":p.maskImage64},p.steps,"Euler a",4,"latent noise",False,"Inpaint a part of image",p.num,1,p.cfg_value,0.75,seed,512,512,
            "Just resize","RealESRGAN",64,False,"Inpaint masked","None",8,4,"fill",False,"Seed","","Steps",""]
        }            
        # colab
        if (Colab):
            j={
                "fn_index":8,
                "data":[p.prompt,None,{"image":p.image64,"mask":p.maskImage64},p.steps,"Euler a",4,"latent noise",False,"Inpaint a part of image",p.num,1,p.cfg_value,0.75,seed,512,512,
                "Just resize","RealESRGAN",64,False,"Inpaint masked","None",8,4,"fill","Seed","","Steps","",False]
            }    
   

    if (p.mode=="txt2img"):
 	   # localhost
        j={
            "fn_index":2,
            "data":[p.prompt,"",p.steps,p.sampling_method,False,p.num,1,p.cfg_value,seed,SDConfig.height,SDConfig.width,"None",False,"Seed","","Steps",""]
        }
        # colab
        if (Colab):
            j={
                "fn_index":2,
            "data":[p.prompt,"",p.steps,p.sampling_method,False,p.num,1,p.cfg_value,seed,SDConfig.height,SDConfig.width,"None","Seed","","Steps","",False]
        }         
    headers = {
```
Pinging @imperator-maximus to see the fix.

**Comment by maxpowersage** [comment] 2022-09-08 00:44
img2img and from text works.  inpainting gives this error:
Traceback (most recent call last):
  File "/home/u/miniconda3/envs/ldm/lib/python3.8/site-packages/gradio/routes.py", line 259, in run_predict
    output = await app.blocks.process_api(
  File "/home/u/miniconda3/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 685, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/u/miniconda3/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 591, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "/home/u/miniconda3/envs/ldm/lib/python3.8/site-packages/gradio/components.py", line 1061, in preprocess
    return self.choices.index(x)
ValueError: 8 is not in list
Any ideas?  I'll really have to dig around to try and debug this one myself.

**Comment by imperator-maximus** [comment] 2022-09-08 01:24
Please use Beta 3, communication has beeen rewritten, so these kind of errors should be fixed now. see https://www.flyingdog.de/sd/en/

**Closed by imperator-maximus** 2022-09-08 01:24 UTC
